name: Deploy to Server

on:
  push:
    branches:
      - main  # Trigger deployment only on pushes to the main branch

jobs:
  deploy:
    name: Deploy Code
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: ${{ secrets.GARDENIA }}

    - name: Deploy to server via SSH
      run: |
        ssh -o StrictHostKeyChecking=no -p 2223 root@195.35.3.165 'bash -s' <<'EOF'
        cd  /home/amp/.ampdata/instances/PixelmonGardenia01/Minecraft/mundo/datapacks/gardenia/
        git pull origin main
        # Any other deployment steps, e.g., restarting services
        EOF
