name: Deploy to Server

on:
  push:
    branches:
      - main  # Trigger on push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        
      - name: Install lftp
        run: sudo apt-get install -y lftp

      - name: Add SFTP Host to Known Hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.SFTP_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to Server via SFTP
        run: |
          lftp -u ${{ secrets.SFTP_USER }},${{ secrets.SFTP_PASSWORD }} -e "set sftp:auto-confirm yes;mirror -R data /mundo/datapacks/gardenia/data; bye" sftp://${{ secrets.SFTP_HOST }}:${{ secrets.SFTP_PORT }}
